export const ADD_GALLERY = 'ADD_GALLERY';
export const REMOVE_GALLERY = "REMOVE_GALLERY";
export const FETCH_GALLERY = "FETCH_GALLERY";
export const FETCH_GALLERY_FAIL = "FETCH_GALLERY_FAIL";
export const FETCH_GALLERY_SUCCESS = "FETCH_GALLERY_SUCCESS"

export const START_FETCH_ART = 'START_FETCH_ART';
export const SET_ART = 'SET_ART';

export const FETCH_ART = 'FETCH_ART';
export const FETCH_ART_FAIL = 'FETCH_ART_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL'; 
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH ';

