export const START_ADD_GALLERY = 'START_ADD_GALLERY'

export const ADD_GALLERY = 'ADD_GALLERY';
export const ADD_GALLERY_FAILED = 'ADD_GALLERY_FAILED'; 
export const ADD_GALLERY_SUCCESS = 'ADD_GALLERY_SUCCESS';
export const ADD_GALLERY_DUPLICATE = 'ADD_GALLERY_DUPLICATE';

export const START_REMOVE_GALLERY = 'START_REMOVE_GALLERY';
export const REMOVE_GALLERY = "REMOVE_GALLERY";
export const REMOVE_GALLERY_SUCCESS = "REMOVE_GALLERY_SUCCESS"; 
export const REMOVE_GALLERY_FAILED = "REMOVE_GALLERY_FAILED"


export const START_FETCH_GALLERY = 'START_FETCH_GALLERY';

export const FETCH_GALLERY = "FETCH_GALLERY";
export const FETCH_GALLERY_FAIL = "FETCH_GALLERY_FAIL";
export const FETCH_GALLERY_SUCCESS = "FETCH_GALLERY_SUCCESS";

export const START_FETCH_ART = 'START_FETCH_ART';
export const SET_ART = 'SET_ART';
export const FETCH_ART = 'FETCH_ART';
export const FETCH_ART_FAIL = 'FETCH_ART_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL'; 
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const START_SAVE_USERNAME= 'START_SAVE_USERNAME';

export const SAVE_USERNAME = 'SAVE_USERNAME'; 
export const SAVE_USERNAME_SUCCESS = 'SAVE_USERNAME_SUCCESS';
export const SAVE_USERNAME_FAIL = 'SAVE_USERNAME_FAIL';



export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH ';

